#!/bin/bash
echo $
mkdir -p "productsWebResource"
rm -rf out/*
rm -rf ./productsWebResource/$1
mv ~/WuNanTech/BSafesV2/BSafes_Frontend_Next/out ./productsWebResource/$1
cp -r ./productsWebResource/$1/* out/.
